version: "3.8"

services:
  
  envoy:
    image: envoyproxy/envoy:v1.16.1
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8001:8001"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml", "--service-cluster", "front-proxy", "-l",  "debug"]
    networks:
      - envoymesh

  service1:
    build: ./service
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=1
  
  service2:
    build: ./service
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=2
  
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - envoymesh
    ports:
      - "9411:9411"
      - "16686:16686"

networks:
  envoymesh: {}